fix: 회원 삭제 시 오류 수정
org.hibernate.TransientObjectException: persistent instance references an unsaved transient instance of 'com.est.runtime.signup.entity.UserLevel' (save the transient instance before flushing)] with root cause

CascadeType 설정으로 인한 오류로, 해당 설정 삭제로 문제 해결.